---
title: "Projects"
---
`r library(icon)`
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

In the summer of 2020 I took a class GIS course based in R. I wrote some code, and did some cool data science. Here is a collection of links! 

## [`r fa("code")` Building a project website](https://github.com/program--/geog176a)

  - For this assignment, we built a static website using **Rmarkdown**.
  - Includes a project github repository for access, view it [here](https://github.com/program--/geog176a) or by clicking on the above header.
  - Deployed project site as separate repo from main website repo using **Netlify**.

## [`r fa("chart-bar")` Tracking COVID-19 Data](https://geog176a.justinsingh.me/labs/lab-02)
  
  - Parsed real-world data using **tidyverse** functions and plotted using **ggplot2**.
  - Used statistical methods for analyzing confirmed COVID-19 cases.
  - Analyzed COVID-19's weighted mean center travel across the United States.
  
## [`r fa("globe-americas")` Analyzing Spatial Data in the US](https://geog176a.justinsingh.me/labs/lab-03)

  - Gathered spatial data about US cities and their relation to national borders using **tidyverse** and **sf** libraries.
  - Used **gghighlight** and **ggplot2** to visualize spatial data, and **sf** to calculate distances.
  - Analyzed controversial Federal Agencies' claims based on an [ACLU article](https://www.aclu.org/other/constitution-100-mile-border-zone) to verify statistics given.
