---
title: "Geography 176A"
author: "[Justin Singh-M.](https://geog176a.justinsingh.me)"
subtitle: 'Lab 05: Flood Risk in Mission Creek: Past, Present, Future'
output:
  html_document:
    theme: sandstone
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include = FALSE}
library(tidyverse)
library(sf)        # vector manipulation
library(raster)    # raster manipulation
library(fasterize) # "faster" raster
library(whitebox)  # terrain analysis

# Data libraries
library(osmdata)   # OSM API
library(elevatr)   # Elevation  Web Tiles

knitr::opts_chunk$set(
    warning = FALSE,
    message = FALSE,
    out.width = "75%",
    fig.align = "center"
)
```

# Collecting Data
```{r}
# Getting Basin Boundary
waterdata <- "https://labs.waterdata.usgs.gov/api/nldi/linked-data/nwissite/USGS-11119750/basin"
basin_boundary <- sf::read_sf(waterdata)
basin_boundary_elev <- elevatr::get_elev_raster(basin_boundary, z = 13) %>%
    raster::crop(basin_boundary)

basin_boundary_elev <- basin_boundary_elev * 3.281 # convert `m` to `ft`

# Comment when file is already written
# raster::writeRaster(basin_boundary_elev, "labs/data/basin-boundary-elev.tif", overwrite = TRUE)

# OSM Data
basin_buildings <- osmdata::opq(basin_boundary) %>%
    add_osm_feature(key = "building") %>%
    osmdata_sf()

basin_buildings <- basin_buildings$osm_polygons %>%
    sf::st_centroid() %>%
    st_intersection(basin_boundary)

# Plot to test if clipping worked as intended
# plot(basin_boundary)
# plot(basin_buildings, max.plot=1, add = TRUE)

basin_railway <- dplyr::filter(basin_buildings, amenity == "railway")

basin_streams <- osmdata::opq(basin_boundary) %>%
    add_osm_feature(key = "waterway", value = "stream") %>%
    osmdata_sf()

basin_streams <- basin_streams$osm_lines %>%
    st_intersection(basin_boundary)

# Plot to test if clipping worked as intended
# plot(basin_boundary)
# plot(basin_streams, max.plot=1, add = TRUE)
```
## {.tabset .tabset-pills .tabset-fade .toc-ignore}
```{r, results = 'asis', echo = FALSE}
cat("\n\n")
cat("### Basin Boundary")
cat("\n\n")
plot(basin_boundary, axes = FALSE, main = "USGS-11119750")
cat("\n\n")
cat("### Basin Buildings")
cat("\n\n")
plot.new()
plot(
    basin_boundary,
    axes = FALSE,
    main = "OSM: building=*"
)
plot(
    basin_buildings,
    axes = FALSE,
    max.plot = 1,
    add = TRUE
)
cat("\n\n")
cat("### Basin Streams")
cat("\n\n")
plot.new()
plot(
    basin_boundary,
    axes = FALSE,
    main = "OSM: waterway=stream"
)
plot(
    basin_streams,
    axes = FALSE,
    max.plot = 1,
    add = TRUE
)
cat("\n\n")
```

# Terrain Analysis
```{r}
whitebox::wbt_hillshade("data/basin-boundary-elev.tif", "data/basin-elev-hillshade.tif")
basin_hillshade <- raster::raster("data/basin-elev-hillshade.tif")

# Plot hillshade (background)
plot(
    basin_hillshade,
    axes = FALSE,
    box = FALSE,
    col = gray.colors(256, alpha = 0.2),
    legend = FALSE,
    main = "Basin Hillshade and Streams"
)
# Plot hillshade (mask)
plot(
    mask(basin_hillshade, basin_boundary),
    col = gray.colors(256, alpha = .8),
    legend = FALSE,
    add = TRUE
)
# Plot basin boundary
plot(
    basin_boundary,
    lty = 3,
    border = "#575757",
    add = TRUE
)
# Plot streams
plot(
    basin_streams,
    max.plot = 1,
    lwd = 2,
    col = "#4852da",
    add = TRUE
)

```

```{r}
buffered_streams <- basin_streams %>%
    st_transform(5070) %>%
    st_buffer(dist = 10) %>%
    st_transform(4326)

streams_raster <- fasterize::fasterize(buffered_streams, basin_boundary_elev)
raster::writeRaster(streams_raster, "labs/data/streams.tif", overwrite = TRUE)

whitebox::wbt_breach_depressions("labs/data/basin-boundary-elev.tif", "labs/data/elev-wbt.tif")

whitebox::wbt_elevation_above_stream("labs/data/elev-wbt.tif", "labs/data/streams.tif", "labs/data/elev-above-streams.tif")

HAND <- raster::raster("labs/data/elev-above-streams.tif")
river_raster <- raster::raster("labs/data/streams.tif")
HAND <- HAND + 3.69

values_with_1 <- which(getValues(river_raster) %in% c(1))
HAND[values_with_1] <- 0
raster::writeRaster(HAND, "labs/data/HAND.tif", overwrite = TRUE)
```
# 2017 Impact Assessment
```{r}
correct_HAND <- raster::raster("labs/data/HAND.tif")
threshold <- function(x) {return(ifelse(x > 10.02, NA, x))}
correct_HAND <- calc(correct_HAND, threshold)

plot.new()
# Plot hillshade (background)
plot(
    basin_hillshade,
    axes = FALSE,
    box = FALSE,
    col = gray.colors(256, alpha = 0.2),
    legend = FALSE,
    main = "Basin Hillshade and Streams"
)
# Plot hillshade (mask)
plot(
    mask(basin_hillshade, basin_boundary),
    col = gray.colors(256, alpha = .8),
    legend = FALSE,
    add = TRUE
)
# Plot basin boundary
plot(
    basin_boundary,
    lty = 3,
    border = "#575757",
    add = TRUE
)
# Plot floods
plot(
    correct_HAND,
    col = rev(blues9),
    add = TRUE
)
# Plot railway
plot(
    basin_railway,
    col = "green",
    cex = 1,
    pch = 16,
    add = TRUE
)

```
```{r}
building_impact <- raster::extract(correct_HAND, basin_buildings)
num_buildings_impacted <- sum(!is.na(building_impact))
buildings <- as.data.frame(basin_buildings)

buildings$impact <- building_impact

basin_buildings <- buildings %>%
    st_as_sf()
# Plot hillshade (background)
plot(
    basin_hillshade,
    axes = FALSE,
    box = FALSE,
    col = gray.colors(256, alpha = 0.2),
    legend = FALSE,
    main = "Basin Hillshade and Streams"
)
# Plot hillshade (mask)
plot(
    mask(basin_hillshade, basin_boundary),
    col = gray.colors(256, alpha = .8),
    legend = FALSE,
    add = TRUE
)
# Plot basin boundary
plot(
    basin_boundary,
    lty = 3,
    border = "#575757",
    add = TRUE
)
# Plot floods
plot(
    correct_HAND,
    col = rev(blues9),
    add = TRUE
)
# Impacted Buildings
plot(
    basin_buildings,
    col = ifelse(is.na(basin_buildings$impact), "black", "red"),
    cex = .08,
    pch = 16,
    add = TRUE
)
# Plot railway
plot(
    basin_railway,
    col = "green",
    cex = 1,
    pch = 16,
    add = TRUE
)
```

# Flood Inudation Map library
```{r}
```